import dynamic from 'next/dynamic'
import Head from 'next/head'
import React, { useState } from 'react'

import { Image } from '@/components/atoms/Image'
import Chat from '@/components/organisms/Chat'
import { Header } from '@/components/organisms/Header'
import { HowTo } from '@/components/organisms/HowTo'
import { Idea } from '@/components/organisms/Idea'
import { Services } from '@/components/organisms/Services'
import type { SideProps } from '@/components/organisms/SideNavbar'
import styles from '@/styles/css/Home.module.css'

const SideNavbar = dynamic<SideProps>(() =>
  import('../components/organisms/SideNavbar').then((mod) => mod.SideNavbar),
)

export default function Home() {
  const [navShown, setNavShown] = useState(false)

  const menuClick = () => {
    setNavShown(!navShown)
  }
  return (
    <div className="">
      <Head>
        <title>
          Buy Instagram Followers and Likes starting at $0.89 - goread.io
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header menuClick={menuClick} navShown={() => navShown} />
      {navShown ? <SideNavbar>abc</SideNavbar> : <div></div>}

      <main className="flex flex-1 flex-col w-full absolute top-0 min-h-screen p-0">
        <div className="min-h-screen">
          <div className="w-full">
            <div className="ml-auto w-8/12">
              <Image
                src="/home-banner.png"
                alt="bannerImage"
                width="100%"
                height="100%"
              />
            </div>
          </div>
          <div className="flex flex-col px-16 pt-10 z-[20] md:pt-0 md:absolute md:top-64 dm:top-56">
            <div className="flex-none md:w-5/12 md:h-auto">
              <h1 className="text-4xl font-medium max-w-full flex flex-wrap">
                <span className="text-[#25AAE1]">Super Real Instagram </span>
                <span>
                  <span>
                    followers, likes, power likes, views, comments,&nbsp;
                  </span>

                  <br></br>
                  <span className="whitespace-nowrap text-[#f15d23]">
                    <span className="text-black">saves&nbsp;</span>
                    <span className="whitespace-nowrap">in Minutes</span>
                  </span>
                </span>
              </h1>
              <br></br>
            </div>
            <p className="flex w-full dm:w-8/12 ml:h-42 mx:w-6/12 mx:h-48 lg:w-5/12 lg:h-36">
              Instagram is one of the best social media platforms to reach
              millions of followers. Buying active and real Instagram increase
              your network of followers naturally. Not only this but you will
              also save your precious time and get the job done in an effortless
              manner.
            </p>
            <div className="flex flex-wrap items-center mt-10 px-2 flex-col space-y-2 md:flex-row md:items-center md:space-x-2 md:space-y-0 lg:px-0">
              <button className="justify-center min-w-[250px] sm:min-w-[60%] md:min-w-min max-w-sm text-white bg-[#25AAE1] px-3 py-2 rounded-3xl hover:text-white hover:bg-[#F15D23] transition-all">
                Buy Instagram Followers
              </button>
              <button className="justify-center min-w-[250px] sm:min-w-[60%] md:min-w-min max-w-sm text-white bg-[#25AAE1] px-3 py-2 rounded-3xl hover:text-white hover:bg-[#F15D23] transition-all">
                Buy Instagram Likes
              </button>
              <button className="justify-center min-w-[250px] sm:min-w-[60%] md:min-w-min max-w-sm text-white bg-[#25AAE1] px-3 py-2 rounded-3xl hover:text-white hover:bg-[#F15D23] transition-all">
                Buy Instagram Views
              </button>
            </div>
            <br></br>
          </div>
        </div>
        <Idea />
        <Services />
        <HowTo />
        <Chat />
      </main>
      <footer className={styles['footer']}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
        </a>
      </footer>
    </div>
  )
}
