import dynamic from 'next/dynamic'
import Head from 'next/head'
import { useState } from 'react'

import type { SideProps } from '@/components/organisms/SideNavbar'

import { Navbar } from './Navbar'

const SideNavbar = dynamic<SideProps>(() =>
  import('@/components/organisms/SideNavbar').then((mod) => mod.SideNavbar),
)

export const Header: React.VFC = () => {
  const [navShown, setNavShown] = useState(false)

  const menuClick = () => {
    setNavShown(!navShown)
  }

  return (
    <>
      <Head>
        <title>
          Buy Instagram Followers and Likes starting at $0.89 - goread.io
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar menuClick={menuClick} isNavShown={navShown} />
      {navShown ? <SideNavbar>abc</SideNavbar> : null}
    </>
  )
}
